version: '3.8'

services:
  # Nginx Reverse Proxy (Micro)
  nginx:
    image: nginx:alpine
    container_name: cvd-nginx-micro
    ports:
      - "80:80"
    volumes:
      - ./nginx.micro.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - cvd-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"

  # Backend API Service (Micro - Essential features only)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.micro
    container_name: cvd-backend-micro
    expose:
      - "8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - LOG_LEVEL=WARNING
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=cvd-micro-secret
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - DISABLE_KAFKA=true
      - DISABLE_REDIS=true
      - MICRO_MODE=true
    volumes:
      - ./backend/data:/app/data
      - ./models:/app/models:ro
    networks:
      - cvd-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 768M
        reservations:
          cpus: '0.2'
          memory: 384M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 60s
      timeout: 15s
      retries: 2
      start_period: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  # Frontend Web Service (Micro - Essential features only)
  frontend:
    build:
      context: ./mobile-app
      dockerfile: Dockerfile.micro
    container_name: cvd-frontend-micro
    expose:
      - "8080"
    environment:
      - NODE_ENV=production
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_APP_API_URL=/api
      - MICRO_MODE=true
    depends_on:
      - backend
    networks:
      - cvd-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"

networks:
  cvd-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# No external volumes to reduce I/O overhead