@echo off
echo Starting CVD Detection Mobile App...
cd /d "%~dp0mobile-app"
echo Installing/updating dependencies...
call npm install
echo Starting Expo development server...
call npx expo start
pause